### PR TITLE
Port glumpy to Python 3.

### PR DESCRIPTION
**Pull request by drufat**
Port all of glumpy to Python 3 while maintaing backward compatibility with Python 2. 
It should now possible to run the examples under python 3.

### CODE REVIEW

**Comment by rougier** [comment]
Waouh ! very impressive, thanks you very much.
I need to test it and I'll merge it. Don't hesitate to ping here if I didn't do it in the next few days.

**Comment by drufat** [comment]
Have you had the chance to review the changes? I've added a few more change and the examples should work as they do under Python 2 without any issues. 

I've had an issue with running the code under an older NVIDIA card on my laptop. I was getting error C0118: macros prefixed with '__' are reserved

So I've prefixed all the occurrences of __VERTEX_SHADER__, __FRAGMENT_SHADER__, __CONSTANTS__ with _GLUMPY.

**Comment by rougier** [comment]
I'm testing but I have to fix a compilation issue with the sdf module and python3

```
from .sdf import *
ImportError: dlopen(/Users/rougier/Development/Public/glumpy/glumpy/ext/sdf/sdf.so, 2): Symbol not found: _PyCObject_Type
  Referenced from: /Users/rougier/Development/Public/glumpy/glumpy/ext/sdf/sdf.so
  Expected in: flat namespace
 in /Users/rougier/Development/Public/glumpy/glumpy/ext/sdf/sdf.so
```

**Comment by drufat** [comment]
You have the `sdf.so` left over from the compilation under pyhton2. Under python3 it would have been named sdf.cpython-34m.so. Did you recompile the extensions under python3 with  `python setup.py build_ext -i`?

**Comment by rougier** [comment]
Yes, but I think my build is wrong:

```
/usr/locaL/Cellar/python3/3.4.3_2/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'platform'
  warnings.warn(msg)
running build_ext
skipping 'glumpy/ext/sdf/_sdf.c' Cython extension (up-to-date)
```

Without the -i, it get installed in ```build```but still with the `.so` extension. I need to investigate.

**Comment by drufat** [comment]
Try starting from a clean state. The steps to take to replicate my build exactly are:

```bash
git clone git@github.com:drufat/glumpy.git
cd glumpy
export PYTHONPATH=. 
python3 setup.py build_ext -i 
for f in `ls examples/*.py`; do python3 $f; done
```

**Comment by rougier** [comment]
Interesting, your method works actually.
Any idea of what to remove in my working directory to make it clean ?

**Comment by drufat** [comment]
I would start by removing `sdf.so`, and rebuilding.

**Comment by rougier** [comment]
I already did that but with no luck. I'll investigate.

**Comment by rougier** [comment]
Seems to be working now. Thanks a lot for this PR.

**Pull request merged**
