### PR TITLE
Added screen kwarg for backend_pyglet.set_fullscreen & backend_qt5 fullscreen getter/setter

### LINKED ISSUE #225: Open fullscreen window on 2nd screen
Hi, 

I want to use glumpy to display a fullscreen window on a 2nd screen while using the pyglet backend. 

In pyglet directly it works without any issues
```
import pyglet
from pyglet import app

display = pyglet.window.get_platform().get_default_display()
screens = display.get_screens()

window = pyglet.window.Window()
window.set_fullscreen(True, screen=screens[1])

app.run()
```

But in glumpy the method app.Window.set_fullscreen does not accept a screen parameter and I haven't found a way of accessing the underlying pyglet.window.Window instance for a direct call of set_fullscreen.

Has anyone maybe had this issue before and can tell me how to do it?

### PR DESCRIPTION
**Pull request by thladnik**
With these changes 

1. the **pyglet backend** would allow for the selection of a screen when switching fullscreen on (this would resolve #225 )
and
2. fullscreen would be enabled for the **qt5 backend** (I was wondering why this doesn't seem to be implemented although it states in the documentation that it should be). I also added separate setter/getter for the screen and an opt. argument for selecting the screen when calling set_fullscreen

### CODE REVIEW

**Comment by rougier** [comment]
Thanks and sorry for the long delay in my answer.
Do you think it can be ported to other "modern" backend  (such as GLFW)?

**Comment by thladnik** [comment]
Sure. I haven't worked with GLFW yet, but I can look into it and try to include it in this pull request.

**Comment by rougier** [comment]
Thanks. That would be great to have GLFW!

**Comment by rougier** [comment]
Fantastic, thanks!

**Pull request merged**
